/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcExchangeOrderField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcExchangeOrderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcExchangeOrderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcExchangeOrderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrderPriceType(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderPriceType_set(swigCPtr, this, value);
  }

  public char getOrderPriceType() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderPriceType_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return ctpJNI.CShfeFtdcExchangeOrderField_Direction_get(swigCPtr, this);
  }

  public void setCombOffsetFlag(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_CombOffsetFlag_set(swigCPtr, this, value);
  }

  public String getCombOffsetFlag() {
    return ctpJNI.CShfeFtdcExchangeOrderField_CombOffsetFlag_get(swigCPtr, this);
  }

  public void setCombHedgeFlag(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_CombHedgeFlag_set(swigCPtr, this, value);
  }

  public String getCombHedgeFlag() {
    return ctpJNI.CShfeFtdcExchangeOrderField_CombHedgeFlag_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    ctpJNI.CShfeFtdcExchangeOrderField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return ctpJNI.CShfeFtdcExchangeOrderField_LimitPrice_get(swigCPtr, this);
  }

  public void setVolumeTotalOriginal(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_VolumeTotalOriginal_set(swigCPtr, this, value);
  }

  public int getVolumeTotalOriginal() {
    return ctpJNI.CShfeFtdcExchangeOrderField_VolumeTotalOriginal_get(swigCPtr, this);
  }

  public void setTimeCondition(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_TimeCondition_set(swigCPtr, this, value);
  }

  public char getTimeCondition() {
    return ctpJNI.CShfeFtdcExchangeOrderField_TimeCondition_get(swigCPtr, this);
  }

  public void setGTDDate(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_GTDDate_set(swigCPtr, this, value);
  }

  public String getGTDDate() {
    return ctpJNI.CShfeFtdcExchangeOrderField_GTDDate_get(swigCPtr, this);
  }

  public void setVolumeCondition(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_VolumeCondition_set(swigCPtr, this, value);
  }

  public char getVolumeCondition() {
    return ctpJNI.CShfeFtdcExchangeOrderField_VolumeCondition_get(swigCPtr, this);
  }

  public void setMinVolume(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_MinVolume_set(swigCPtr, this, value);
  }

  public int getMinVolume() {
    return ctpJNI.CShfeFtdcExchangeOrderField_MinVolume_get(swigCPtr, this);
  }

  public void setContingentCondition(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ContingentCondition_set(swigCPtr, this, value);
  }

  public char getContingentCondition() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ContingentCondition_get(swigCPtr, this);
  }

  public void setStopPrice(double value) {
    ctpJNI.CShfeFtdcExchangeOrderField_StopPrice_set(swigCPtr, this, value);
  }

  public double getStopPrice() {
    return ctpJNI.CShfeFtdcExchangeOrderField_StopPrice_get(swigCPtr, this);
  }

  public void setForceCloseReason(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ForceCloseReason_set(swigCPtr, this, value);
  }

  public char getForceCloseReason() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ForceCloseReason_get(swigCPtr, this);
  }

  public void setIsAutoSuspend(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_IsAutoSuspend_set(swigCPtr, this, value);
  }

  public int getIsAutoSuspend() {
    return ctpJNI.CShfeFtdcExchangeOrderField_IsAutoSuspend_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return ctpJNI.CShfeFtdcExchangeOrderField_BusinessUnit_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_RequestID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_InstallID_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return ctpJNI.CShfeFtdcExchangeOrderField_NotifySequence_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpJNI.CShfeFtdcExchangeOrderField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_SettlementID_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderSysID_get(swigCPtr, this);
  }

  public void setOrderSource(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderSource_set(swigCPtr, this, value);
  }

  public char getOrderSource() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderSource_get(swigCPtr, this);
  }

  public void setOrderStatus(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderStatus_set(swigCPtr, this, value);
  }

  public char getOrderStatus() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderStatus_get(swigCPtr, this);
  }

  public void setOrderType(char value) {
    ctpJNI.CShfeFtdcExchangeOrderField_OrderType_set(swigCPtr, this, value);
  }

  public char getOrderType() {
    return ctpJNI.CShfeFtdcExchangeOrderField_OrderType_get(swigCPtr, this);
  }

  public void setVolumeTraded(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_VolumeTraded_set(swigCPtr, this, value);
  }

  public int getVolumeTraded() {
    return ctpJNI.CShfeFtdcExchangeOrderField_VolumeTraded_get(swigCPtr, this);
  }

  public void setVolumeTotal(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_VolumeTotal_set(swigCPtr, this, value);
  }

  public int getVolumeTotal() {
    return ctpJNI.CShfeFtdcExchangeOrderField_VolumeTotal_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return ctpJNI.CShfeFtdcExchangeOrderField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return ctpJNI.CShfeFtdcExchangeOrderField_InsertTime_get(swigCPtr, this);
  }

  public void setActiveTime(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ActiveTime_set(swigCPtr, this, value);
  }

  public String getActiveTime() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ActiveTime_get(swigCPtr, this);
  }

  public void setSuspendTime(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_SuspendTime_set(swigCPtr, this, value);
  }

  public String getSuspendTime() {
    return ctpJNI.CShfeFtdcExchangeOrderField_SuspendTime_get(swigCPtr, this);
  }

  public void setUpdateTime(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_UpdateTime_set(swigCPtr, this, value);
  }

  public String getUpdateTime() {
    return ctpJNI.CShfeFtdcExchangeOrderField_UpdateTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return ctpJNI.CShfeFtdcExchangeOrderField_CancelTime_get(swigCPtr, this);
  }

  public void setActiveTraderID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ActiveTraderID_set(swigCPtr, this, value);
  }

  public String getActiveTraderID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ActiveTraderID_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    ctpJNI.CShfeFtdcExchangeOrderField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return ctpJNI.CShfeFtdcExchangeOrderField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    ctpJNI.CShfeFtdcExchangeOrderField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpJNI.CShfeFtdcExchangeOrderField_SequenceNo_get(swigCPtr, this);
  }

  public CShfeFtdcExchangeOrderField() {
    this(ctpJNI.new_CShfeFtdcExchangeOrderField(), true);
  }

}
