/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcInvestorLinkManField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcInvestorLinkManField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcInvestorLinkManField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcInvestorLinkManField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_InvestorID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorGroupID(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_InvestorGroupID_set(swigCPtr, this, value);
  }

  public String getInvestorGroupID() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_InvestorGroupID_get(swigCPtr, this);
  }

  public void setInvestorName(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_InvestorName_set(swigCPtr, this, value);
  }

  public String getInvestorName() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_InvestorName_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_IsActive_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_Address_get(swigCPtr, this);
  }

  public void setOrderManIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManIdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getOrderManIdentifiedCardType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManIdentifiedCardType_get(swigCPtr, this);
  }

  public void setOrderManIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManIdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getOrderManIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManIdentifiedCardNo_get(swigCPtr, this);
  }

  public void setOrderManPersonName(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManPersonName_set(swigCPtr, this, value);
  }

  public String getOrderManPersonName() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManPersonName_get(swigCPtr, this);
  }

  public void setOrderManTelephone(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManTelephone_set(swigCPtr, this, value);
  }

  public String getOrderManTelephone() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManTelephone_get(swigCPtr, this);
  }

  public void setOrderManAddress(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManAddress_set(swigCPtr, this, value);
  }

  public String getOrderManAddress() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManAddress_get(swigCPtr, this);
  }

  public void setOrderManZipCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderManZipCode_set(swigCPtr, this, value);
  }

  public String getOrderManZipCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderManZipCode_get(swigCPtr, this);
  }

  public void setFundManIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManIdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getFundManIdentifiedCardType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManIdentifiedCardType_get(swigCPtr, this);
  }

  public void setFundManIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManIdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getFundManIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManIdentifiedCardNo_get(swigCPtr, this);
  }

  public void setFundManPersonName(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManPersonName_set(swigCPtr, this, value);
  }

  public String getFundManPersonName() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManPersonName_get(swigCPtr, this);
  }

  public void setFundManTelephone(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManTelephone_set(swigCPtr, this, value);
  }

  public String getFundManTelephone() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManTelephone_get(swigCPtr, this);
  }

  public void setFundManAddress(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManAddress_set(swigCPtr, this, value);
  }

  public String getFundManAddress() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManAddress_get(swigCPtr, this);
  }

  public void setFundManZipCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundManZipCode_set(swigCPtr, this, value);
  }

  public String getFundManZipCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundManZipCode_get(swigCPtr, this);
  }

  public void setOpenManIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManIdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getOpenManIdentifiedCardType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManIdentifiedCardType_get(swigCPtr, this);
  }

  public void setOpenManIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManIdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getOpenManIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManIdentifiedCardNo_get(swigCPtr, this);
  }

  public void setOpenManPersonName(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManPersonName_set(swigCPtr, this, value);
  }

  public String getOpenManPersonName() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManPersonName_get(swigCPtr, this);
  }

  public void setOpenManTelephone(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManTelephone_set(swigCPtr, this, value);
  }

  public String getOpenManTelephone() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManTelephone_get(swigCPtr, this);
  }

  public void setOpenManAddress(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManAddress_set(swigCPtr, this, value);
  }

  public String getOpenManAddress() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManAddress_get(swigCPtr, this);
  }

  public void setOpenManZipCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenManZipCode_set(swigCPtr, this, value);
  }

  public String getOpenManZipCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenManZipCode_get(swigCPtr, this);
  }

  public void setSettlementManIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManIdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getSettlementManIdentifiedCardType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManIdentifiedCardType_get(swigCPtr, this);
  }

  public void setSettlementManIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManIdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getSettlementManIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManIdentifiedCardNo_get(swigCPtr, this);
  }

  public void setSettlementManPersonName(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManPersonName_set(swigCPtr, this, value);
  }

  public String getSettlementManPersonName() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManPersonName_get(swigCPtr, this);
  }

  public void setSettlementManTelephone(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManTelephone_set(swigCPtr, this, value);
  }

  public String getSettlementManTelephone() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManTelephone_get(swigCPtr, this);
  }

  public void setSettlementManAddress(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManAddress_set(swigCPtr, this, value);
  }

  public String getSettlementManAddress() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManAddress_get(swigCPtr, this);
  }

  public void setSettlementManZipCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManZipCode_set(swigCPtr, this, value);
  }

  public String getSettlementManZipCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlementManZipCode_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenDate_get(swigCPtr, this);
  }

  public void setMobile(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_Mobile_set(swigCPtr, this, value);
  }

  public String getMobile() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_Mobile_get(swigCPtr, this);
  }

  public void setEMail(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_EMail_set(swigCPtr, this, value);
  }

  public String getEMail() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_EMail_get(swigCPtr, this);
  }

  public void setInvestorType(char value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_InvestorType_set(swigCPtr, this, value);
  }

  public char getInvestorType() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_InvestorType_get(swigCPtr, this);
  }

  public void setPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_PhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getPhoneCountryCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_PhoneCountryCode_get(swigCPtr, this);
  }

  public void setPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_PhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getPhoneAreaCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_PhoneAreaCode_get(swigCPtr, this);
  }

  public void setOpenPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getOpenPhoneCountryCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenPhoneCountryCode_get(swigCPtr, this);
  }

  public void setOpenPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OpenPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getOpenPhoneAreaCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OpenPhoneAreaCode_get(swigCPtr, this);
  }

  public void setOrderPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getOrderPhoneCountryCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderPhoneCountryCode_get(swigCPtr, this);
  }

  public void setOrderPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_OrderPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getOrderPhoneAreaCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_OrderPhoneAreaCode_get(swigCPtr, this);
  }

  public void setFundPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getFundPhoneCountryCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundPhoneCountryCode_get(swigCPtr, this);
  }

  public void setFundPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_FundPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getFundPhoneAreaCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_FundPhoneAreaCode_get(swigCPtr, this);
  }

  public void setSettlePhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlePhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getSettlePhoneCountryCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlePhoneCountryCode_get(swigCPtr, this);
  }

  public void setSettlePhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcInvestorLinkManField_SettlePhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getSettlePhoneAreaCode() {
    return ctpJNI.CShfeFtdcInvestorLinkManField_SettlePhoneAreaCode_get(swigCPtr, this);
  }

  public CShfeFtdcInvestorLinkManField() {
    this(ctpJNI.new_CShfeFtdcInvestorLinkManField(), true);
  }

}
