/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcTradeStatField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcTradeStatField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcTradeStatField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcTradeStatField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcTradeStatField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcTradeStatField_BrokerID_get(swigCPtr, this);
  }

  public void setExchangeProductInstID(String value) {
    ctpJNI.CShfeFtdcTradeStatField_ExchangeProductInstID_set(swigCPtr, this, value);
  }

  public String getExchangeProductInstID() {
    return ctpJNI.CShfeFtdcTradeStatField_ExchangeProductInstID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcTradeStatField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcTradeStatField_InvestorID_get(swigCPtr, this);
  }

  public void setTotalVol(int value) {
    ctpJNI.CShfeFtdcTradeStatField_TotalVol_set(swigCPtr, this, value);
  }

  public int getTotalVol() {
    return ctpJNI.CShfeFtdcTradeStatField_TotalVol_get(swigCPtr, this);
  }

  public void setTotalAmt(double value) {
    ctpJNI.CShfeFtdcTradeStatField_TotalAmt_set(swigCPtr, this, value);
  }

  public double getTotalAmt() {
    return ctpJNI.CShfeFtdcTradeStatField_TotalAmt_get(swigCPtr, this);
  }

  public void setBuyVol(int value) {
    ctpJNI.CShfeFtdcTradeStatField_BuyVol_set(swigCPtr, this, value);
  }

  public int getBuyVol() {
    return ctpJNI.CShfeFtdcTradeStatField_BuyVol_get(swigCPtr, this);
  }

  public void setBuyAmt(double value) {
    ctpJNI.CShfeFtdcTradeStatField_BuyAmt_set(swigCPtr, this, value);
  }

  public double getBuyAmt() {
    return ctpJNI.CShfeFtdcTradeStatField_BuyAmt_get(swigCPtr, this);
  }

  public void setSellVol(int value) {
    ctpJNI.CShfeFtdcTradeStatField_SellVol_set(swigCPtr, this, value);
  }

  public int getSellVol() {
    return ctpJNI.CShfeFtdcTradeStatField_SellVol_get(swigCPtr, this);
  }

  public void setSellAmt(double value) {
    ctpJNI.CShfeFtdcTradeStatField_SellAmt_set(swigCPtr, this, value);
  }

  public double getSellAmt() {
    return ctpJNI.CShfeFtdcTradeStatField_SellAmt_get(swigCPtr, this);
  }

  public void setNetVol(int value) {
    ctpJNI.CShfeFtdcTradeStatField_NetVol_set(swigCPtr, this, value);
  }

  public int getNetVol() {
    return ctpJNI.CShfeFtdcTradeStatField_NetVol_get(swigCPtr, this);
  }

  public void setNetAmt(double value) {
    ctpJNI.CShfeFtdcTradeStatField_NetAmt_set(swigCPtr, this, value);
  }

  public double getNetAmt() {
    return ctpJNI.CShfeFtdcTradeStatField_NetAmt_get(swigCPtr, this);
  }

  public CShfeFtdcTradeStatField() {
    this(ctpJNI.new_CShfeFtdcTradeStatField(), true);
  }

}
