/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcNoticeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcNoticeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcNoticeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcNoticeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcNoticeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcNoticeField_BrokerID_get(swigCPtr, this);
  }

  public void setContent(String value) {
    ctpJNI.CShfeFtdcNoticeField_Content_set(swigCPtr, this, value);
  }

  public String getContent() {
    return ctpJNI.CShfeFtdcNoticeField_Content_get(swigCPtr, this);
  }

  public void setSequenceLabel(String value) {
    ctpJNI.CShfeFtdcNoticeField_SequenceLabel_set(swigCPtr, this, value);
  }

  public String getSequenceLabel() {
    return ctpJNI.CShfeFtdcNoticeField_SequenceLabel_get(swigCPtr, this);
  }

  public CShfeFtdcNoticeField() {
    this(ctpJNI.new_CShfeFtdcNoticeField(), true);
  }

}
