/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRiskNotifyTokenField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRiskNotifyTokenField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRiskNotifyTokenField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRiskNotifyTokenField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setToken(String value) {
    ctpJNI.CShfeFtdcRiskNotifyTokenField_Token_set(swigCPtr, this, value);
  }

  public String getToken() {
    return ctpJNI.CShfeFtdcRiskNotifyTokenField_Token_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    ctpJNI.CShfeFtdcRiskNotifyTokenField_Description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return ctpJNI.CShfeFtdcRiskNotifyTokenField_Description_get(swigCPtr, this);
  }

  public CShfeFtdcRiskNotifyTokenField() {
    this(ctpJNI.new_CShfeFtdcRiskNotifyTokenField(), true);
  }

}
