/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRspLocalFrontLoginField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRspLocalFrontLoginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRspLocalFrontLoginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRspLocalFrontLoginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCommPhaseNo(short value) {
    ctpJNI.CShfeFtdcRspLocalFrontLoginField_CommPhaseNo_set(swigCPtr, this, value);
  }

  public short getCommPhaseNo() {
    return ctpJNI.CShfeFtdcRspLocalFrontLoginField_CommPhaseNo_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRspLocalFrontLoginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRspLocalFrontLoginField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpJNI.CShfeFtdcRspLocalFrontLoginField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpJNI.CShfeFtdcRspLocalFrontLoginField_UserID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    ctpJNI.CShfeFtdcRspLocalFrontLoginField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return ctpJNI.CShfeFtdcRspLocalFrontLoginField_FrontID_get(swigCPtr, this);
  }

  public void setFrontSessionID(int value) {
    ctpJNI.CShfeFtdcRspLocalFrontLoginField_FrontSessionID_set(swigCPtr, this, value);
  }

  public int getFrontSessionID() {
    return ctpJNI.CShfeFtdcRspLocalFrontLoginField_FrontSessionID_get(swigCPtr, this);
  }

  public CShfeFtdcRspLocalFrontLoginField() {
    this(ctpJNI.new_CShfeFtdcRspLocalFrontLoginField(), true);
  }

}
