/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcSeqPreRiskAccountField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcSeqPreRiskAccountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcSeqPreRiskAccountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcSeqPreRiskAccountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUniqSequenceNo(int value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_UniqSequenceNo_set(swigCPtr, this, value);
  }

  public int getUniqSequenceNo() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_UniqSequenceNo_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_InvestorID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_AccountID_get(swigCPtr, this);
  }

  public void setPreMortgage(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreMortgage_set(swigCPtr, this, value);
  }

  public double getPreMortgage() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreMortgage_get(swigCPtr, this);
  }

  public void setPreCredit(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreCredit_set(swigCPtr, this, value);
  }

  public double getPreCredit() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreCredit_get(swigCPtr, this);
  }

  public void setPreDeposit(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreDeposit_set(swigCPtr, this, value);
  }

  public double getPreDeposit() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreDeposit_get(swigCPtr, this);
  }

  public void setPreBalance(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreBalance_set(swigCPtr, this, value);
  }

  public double getPreBalance() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreBalance_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreMargin_get(swigCPtr, this);
  }

  public void setReserve(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_Reserve_set(swigCPtr, this, value);
  }

  public double getReserve() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_Reserve_get(swigCPtr, this);
  }

  public void setPreExchMargin(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreExchMargin_set(swigCPtr, this, value);
  }

  public double getPreExchMargin() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_PreExchMargin_get(swigCPtr, this);
  }

  public void setForceCloseStat(int value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_ForceCloseStat_set(swigCPtr, this, value);
  }

  public int getForceCloseStat() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_ForceCloseStat_get(swigCPtr, this);
  }

  public void setDeliveryMargin(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_DeliveryMargin_set(swigCPtr, this, value);
  }

  public double getDeliveryMargin() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_DeliveryMargin_get(swigCPtr, this);
  }

  public void setExchangeDeliveryMargin(double value) {
    ctpJNI.CShfeFtdcSeqPreRiskAccountField_ExchangeDeliveryMargin_set(swigCPtr, this, value);
  }

  public double getExchangeDeliveryMargin() {
    return ctpJNI.CShfeFtdcSeqPreRiskAccountField_ExchangeDeliveryMargin_get(swigCPtr, this);
  }

  public CShfeFtdcSeqPreRiskAccountField() {
    this(ctpJNI.new_CShfeFtdcSeqPreRiskAccountField(), true);
  }

}
