/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcReqUserLoginField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcReqUserLoginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcReqUserLoginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcReqUserLoginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpJNI.CShfeFtdcReqUserLoginField_TradingDay_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcReqUserLoginField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpJNI.CShfeFtdcReqUserLoginField_UserID_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ctpJNI.CShfeFtdcReqUserLoginField_Password_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return ctpJNI.CShfeFtdcReqUserLoginField_UserProductInfo_get(swigCPtr, this);
  }

  public void setInterfaceProductInfo(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_InterfaceProductInfo_set(swigCPtr, this, value);
  }

  public String getInterfaceProductInfo() {
    return ctpJNI.CShfeFtdcReqUserLoginField_InterfaceProductInfo_get(swigCPtr, this);
  }

  public void setProtocolInfo(String value) {
    ctpJNI.CShfeFtdcReqUserLoginField_ProtocolInfo_set(swigCPtr, this, value);
  }

  public String getProtocolInfo() {
    return ctpJNI.CShfeFtdcReqUserLoginField_ProtocolInfo_get(swigCPtr, this);
  }

  public CShfeFtdcReqUserLoginField() {
    this(ctpJNI.new_CShfeFtdcReqUserLoginField(), true);
  }

}
