/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRiskParkedOrderField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRiskParkedOrderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRiskParkedOrderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRiskParkedOrderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParkedOrderID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ParkedOrderID_set(swigCPtr, this, value);
  }

  public String getParkedOrderID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ParkedOrderID_get(swigCPtr, this);
  }

  public void setLocalID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_LocalID_set(swigCPtr, this, value);
  }

  public String getLocalID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_LocalID_get(swigCPtr, this);
  }

  public void setUserType(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_UserType_set(swigCPtr, this, value);
  }

  public char getUserType() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_UserType_get(swigCPtr, this);
  }

  public void setStatus(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Status_set(swigCPtr, this, value);
  }

  public char getStatus() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Status_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_StatusMsg_get(swigCPtr, this);
  }

  public void setTriggerType(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_TriggerType_set(swigCPtr, this, value);
  }

  public char getTriggerType() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_TriggerType_get(swigCPtr, this);
  }

  public void setTradeSegment(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_TradeSegment_set(swigCPtr, this, value);
  }

  public int getTradeSegment() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_TradeSegment_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ExchangeID_get(swigCPtr, this);
  }

  public void setFCType(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_FCType_set(swigCPtr, this, value);
  }

  public char getFCType() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_FCType_get(swigCPtr, this);
  }

  public void setTime1(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Time1_set(swigCPtr, this, value);
  }

  public String getTime1() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Time1_get(swigCPtr, this);
  }

  public void setMillisec1(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Millisec1_set(swigCPtr, this, value);
  }

  public int getMillisec1() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Millisec1_get(swigCPtr, this);
  }

  public void setTime2(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Time2_set(swigCPtr, this, value);
  }

  public String getTime2() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Time2_get(swigCPtr, this);
  }

  public void setMillisec2(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Millisec2_set(swigCPtr, this, value);
  }

  public int getMillisec2() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Millisec2_get(swigCPtr, this);
  }

  public void setFCSceneId(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_FCSceneId_set(swigCPtr, this, value);
  }

  public String getFCSceneId() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_FCSceneId_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_InstrumentID_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OrderRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_UserID_get(swigCPtr, this);
  }

  public void setOrderPriceType(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OrderPriceType_set(swigCPtr, this, value);
  }

  public char getOrderPriceType() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OrderPriceType_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Direction_get(swigCPtr, this);
  }

  public void setCombOffsetFlag(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_CombOffsetFlag_set(swigCPtr, this, value);
  }

  public String getCombOffsetFlag() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_CombOffsetFlag_get(swigCPtr, this);
  }

  public void setCombHedgeFlag(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_CombHedgeFlag_set(swigCPtr, this, value);
  }

  public String getCombHedgeFlag() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_CombHedgeFlag_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_LimitPrice_get(swigCPtr, this);
  }

  public void setVolumeTotalOriginal(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_VolumeTotalOriginal_set(swigCPtr, this, value);
  }

  public int getVolumeTotalOriginal() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_VolumeTotalOriginal_get(swigCPtr, this);
  }

  public void setTimeCondition(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_TimeCondition_set(swigCPtr, this, value);
  }

  public char getTimeCondition() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_TimeCondition_get(swigCPtr, this);
  }

  public void setGTDDate(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_GTDDate_set(swigCPtr, this, value);
  }

  public String getGTDDate() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_GTDDate_get(swigCPtr, this);
  }

  public void setVolumeCondition(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_VolumeCondition_set(swigCPtr, this, value);
  }

  public char getVolumeCondition() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_VolumeCondition_get(swigCPtr, this);
  }

  public void setMinVolume(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_MinVolume_set(swigCPtr, this, value);
  }

  public int getMinVolume() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_MinVolume_get(swigCPtr, this);
  }

  public void setContingentCondition(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ContingentCondition_set(swigCPtr, this, value);
  }

  public char getContingentCondition() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ContingentCondition_get(swigCPtr, this);
  }

  public void setStopPrice(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_StopPrice_set(swigCPtr, this, value);
  }

  public double getStopPrice() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_StopPrice_get(swigCPtr, this);
  }

  public void setForceCloseReason(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ForceCloseReason_set(swigCPtr, this, value);
  }

  public char getForceCloseReason() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ForceCloseReason_get(swigCPtr, this);
  }

  public void setIsAutoSuspend(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_IsAutoSuspend_set(swigCPtr, this, value);
  }

  public int getIsAutoSuspend() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_IsAutoSuspend_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_BusinessUnit_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_RequestID_get(swigCPtr, this);
  }

  public void setUserForceClose(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_UserForceClose_set(swigCPtr, this, value);
  }

  public int getUserForceClose() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_UserForceClose_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setOrderStatus(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OrderStatus_set(swigCPtr, this, value);
  }

  public char getOrderStatus() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OrderStatus_get(swigCPtr, this);
  }

  public void setOrderStatusMsg(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OrderStatusMsg_set(swigCPtr, this, value);
  }

  public String getOrderStatusMsg() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OrderStatusMsg_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ErrorMsg_get(swigCPtr, this);
  }

  public void setParkedTime(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ParkedTime_set(swigCPtr, this, value);
  }

  public String getParkedTime() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ParkedTime_get(swigCPtr, this);
  }

  public void setOriginalParkedVol(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_OriginalParkedVol_set(swigCPtr, this, value);
  }

  public int getOriginalParkedVol() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_OriginalParkedVol_get(swigCPtr, this);
  }

  public void setMaxCloseVol1(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_MaxCloseVol1_set(swigCPtr, this, value);
  }

  public int getMaxCloseVol1() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_MaxCloseVol1_get(swigCPtr, this);
  }

  public void setMaxCloseVol2(int value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_MaxCloseVol2_set(swigCPtr, this, value);
  }

  public int getMaxCloseVol2() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_MaxCloseVol2_get(swigCPtr, this);
  }

  public void setCall1(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Call1_set(swigCPtr, this, value);
  }

  public double getCall1() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Call1_get(swigCPtr, this);
  }

  public void setCall2(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_Call2_set(swigCPtr, this, value);
  }

  public double getCall2() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_Call2_get(swigCPtr, this);
  }

  public void setMoneyIO1(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_MoneyIO1_set(swigCPtr, this, value);
  }

  public double getMoneyIO1() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_MoneyIO1_get(swigCPtr, this);
  }

  public void setMoneyIO2(double value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_MoneyIO2_set(swigCPtr, this, value);
  }

  public double getMoneyIO2() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_MoneyIO2_get(swigCPtr, this);
  }

  public void setDeleteReason(String value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_DeleteReason_set(swigCPtr, this, value);
  }

  public String getDeleteReason() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_DeleteReason_get(swigCPtr, this);
  }

  public void setForceCloseRelease(char value) {
    ctpJNI.CShfeFtdcRiskParkedOrderField_ForceCloseRelease_set(swigCPtr, this, value);
  }

  public char getForceCloseRelease() {
    return ctpJNI.CShfeFtdcRiskParkedOrderField_ForceCloseRelease_get(swigCPtr, this);
  }

  public CShfeFtdcRiskParkedOrderField() {
    this(ctpJNI.new_CShfeFtdcRiskParkedOrderField(), true);
  }

}
