/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcInvestorSumInfoField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcInvestorSumInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcInvestorSumInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcInvestorSumInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCount(int value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_Count_set(swigCPtr, this, value);
  }

  public int getCount() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_Count_get(swigCPtr, this);
  }

  public void setMd5_1(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_1_set(swigCPtr, this, value);
  }

  public char getMd5_1() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_1_get(swigCPtr, this);
  }

  public void setMd5_2(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_2_set(swigCPtr, this, value);
  }

  public char getMd5_2() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_2_get(swigCPtr, this);
  }

  public void setMd5_3(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_3_set(swigCPtr, this, value);
  }

  public char getMd5_3() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_3_get(swigCPtr, this);
  }

  public void setMd5_4(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_4_set(swigCPtr, this, value);
  }

  public char getMd5_4() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_4_get(swigCPtr, this);
  }

  public void setMd5_5(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_5_set(swigCPtr, this, value);
  }

  public char getMd5_5() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_5_get(swigCPtr, this);
  }

  public void setMd5_6(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_6_set(swigCPtr, this, value);
  }

  public char getMd5_6() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_6_get(swigCPtr, this);
  }

  public void setMd5_7(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_7_set(swigCPtr, this, value);
  }

  public char getMd5_7() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_7_get(swigCPtr, this);
  }

  public void setMd5_8(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_8_set(swigCPtr, this, value);
  }

  public char getMd5_8() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_8_get(swigCPtr, this);
  }

  public void setMd5_9(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_9_set(swigCPtr, this, value);
  }

  public char getMd5_9() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_9_get(swigCPtr, this);
  }

  public void setMd5_10(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_10_set(swigCPtr, this, value);
  }

  public char getMd5_10() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_10_get(swigCPtr, this);
  }

  public void setMd5_11(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_11_set(swigCPtr, this, value);
  }

  public char getMd5_11() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_11_get(swigCPtr, this);
  }

  public void setMd5_12(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_12_set(swigCPtr, this, value);
  }

  public char getMd5_12() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_12_get(swigCPtr, this);
  }

  public void setMd5_13(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_13_set(swigCPtr, this, value);
  }

  public char getMd5_13() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_13_get(swigCPtr, this);
  }

  public void setMd5_14(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_14_set(swigCPtr, this, value);
  }

  public char getMd5_14() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_14_get(swigCPtr, this);
  }

  public void setMd5_15(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_15_set(swigCPtr, this, value);
  }

  public char getMd5_15() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_15_get(swigCPtr, this);
  }

  public void setMd5_16(char value) {
    ctpJNI.CShfeFtdcInvestorSumInfoField_md5_16_set(swigCPtr, this, value);
  }

  public char getMd5_16() {
    return ctpJNI.CShfeFtdcInvestorSumInfoField_md5_16_get(swigCPtr, this);
  }

  public CShfeFtdcInvestorSumInfoField() {
    this(ctpJNI.new_CShfeFtdcInvestorSumInfoField(), true);
  }

}
