/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcMarketDataBid23Field {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcMarketDataBid23Field(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcMarketDataBid23Field obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcMarketDataBid23Field(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBidPrice2(double value) {
    ctpJNI.CShfeFtdcMarketDataBid23Field_BidPrice2_set(swigCPtr, this, value);
  }

  public double getBidPrice2() {
    return ctpJNI.CShfeFtdcMarketDataBid23Field_BidPrice2_get(swigCPtr, this);
  }

  public void setBidVolume2(int value) {
    ctpJNI.CShfeFtdcMarketDataBid23Field_BidVolume2_set(swigCPtr, this, value);
  }

  public int getBidVolume2() {
    return ctpJNI.CShfeFtdcMarketDataBid23Field_BidVolume2_get(swigCPtr, this);
  }

  public void setBidPrice3(double value) {
    ctpJNI.CShfeFtdcMarketDataBid23Field_BidPrice3_set(swigCPtr, this, value);
  }

  public double getBidPrice3() {
    return ctpJNI.CShfeFtdcMarketDataBid23Field_BidPrice3_get(swigCPtr, this);
  }

  public void setBidVolume3(int value) {
    ctpJNI.CShfeFtdcMarketDataBid23Field_BidVolume3_set(swigCPtr, this, value);
  }

  public int getBidVolume3() {
    return ctpJNI.CShfeFtdcMarketDataBid23Field_BidVolume3_get(swigCPtr, this);
  }

  public CShfeFtdcMarketDataBid23Field() {
    this(ctpJNI.new_CShfeFtdcMarketDataBid23Field(), true);
  }

}
