/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public final class TE_RESUME_TYPE {
  public final static TE_RESUME_TYPE TERT_RESTART = new TE_RESUME_TYPE("TERT_RESTART", ctpJNI.TERT_RESTART_get());
  public final static TE_RESUME_TYPE TERT_RESUME = new TE_RESUME_TYPE("TERT_RESUME");
  public final static TE_RESUME_TYPE TERT_QUICK = new TE_RESUME_TYPE("TERT_QUICK");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TE_RESUME_TYPE swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TE_RESUME_TYPE.class + " with value " + swigValue);
  }

  private TE_RESUME_TYPE(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TE_RESUME_TYPE(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TE_RESUME_TYPE(String swigName, TE_RESUME_TYPE swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TE_RESUME_TYPE[] swigValues = { TERT_RESTART, TERT_RESUME, TERT_QUICK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

