/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcProductLimitsField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcProductLimitsField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcProductLimitsField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcProductLimitsField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductID(String value) {
    ctpJNI.CShfeFtdcProductLimitsField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return ctpJNI.CShfeFtdcProductLimitsField_ProductID_get(swigCPtr, this);
  }

  public void setLimit1(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_Limit1_set(swigCPtr, this, value);
  }

  public double getLimit1() {
    return ctpJNI.CShfeFtdcProductLimitsField_Limit1_get(swigCPtr, this);
  }

  public void setLimit2(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_Limit2_set(swigCPtr, this, value);
  }

  public double getLimit2() {
    return ctpJNI.CShfeFtdcProductLimitsField_Limit2_get(swigCPtr, this);
  }

  public void setLimit3(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_Limit3_set(swigCPtr, this, value);
  }

  public double getLimit3() {
    return ctpJNI.CShfeFtdcProductLimitsField_Limit3_get(swigCPtr, this);
  }

  public void setLimit4(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_Limit4_set(swigCPtr, this, value);
  }

  public double getLimit4() {
    return ctpJNI.CShfeFtdcProductLimitsField_Limit4_get(swigCPtr, this);
  }

  public void setMaxMarginRate1(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_MaxMarginRate1_set(swigCPtr, this, value);
  }

  public double getMaxMarginRate1() {
    return ctpJNI.CShfeFtdcProductLimitsField_MaxMarginRate1_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    ctpJNI.CShfeFtdcProductLimitsField_Price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return ctpJNI.CShfeFtdcProductLimitsField_Price_get(swigCPtr, this);
  }

  public CShfeFtdcProductLimitsField() {
    this(ctpJNI.new_CShfeFtdcProductLimitsField(), true);
  }

}
