/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRspSafePriceRangeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRspSafePriceRangeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRspSafePriceRangeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRspSafePriceRangeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_InstrumentID_get(swigCPtr, this);
  }

  public void setBasePrice(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_BasePrice_set(swigCPtr, this, value);
  }

  public double getBasePrice() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_BasePrice_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitPrice_get(swigCPtr, this);
  }

  public void setVaryPecent(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_VaryPecent_set(swigCPtr, this, value);
  }

  public double getVaryPecent() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_VaryPecent_get(swigCPtr, this);
  }

  public void setLimitDayCnt(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitDayCnt_set(swigCPtr, this, value);
  }

  public int getLimitDayCnt() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitDayCnt_get(swigCPtr, this);
  }

  public void setVaryTickCnt(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_VaryTickCnt_set(swigCPtr, this, value);
  }

  public int getVaryTickCnt() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_VaryTickCnt_get(swigCPtr, this);
  }

  public void setLimitTickCnt(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitTickCnt_set(swigCPtr, this, value);
  }

  public int getLimitTickCnt() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_LimitTickCnt_get(swigCPtr, this);
  }

  public void setHasLimit(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_HasLimit_set(swigCPtr, this, value);
  }

  public int getHasLimit() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_HasLimit_get(swigCPtr, this);
  }

  public void setPecentPerLimit(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_PecentPerLimit_set(swigCPtr, this, value);
  }

  public double getPecentPerLimit() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_PecentPerLimit_get(swigCPtr, this);
  }

  public void setInLimitVaryPct(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_InLimitVaryPct_set(swigCPtr, this, value);
  }

  public double getInLimitVaryPct() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_InLimitVaryPct_get(swigCPtr, this);
  }

  public void setOutLimitVaryPct(double value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_OutLimitVaryPct_set(swigCPtr, this, value);
  }

  public double getOutLimitVaryPct() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_OutLimitVaryPct_get(swigCPtr, this);
  }

  public void setLongVol(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_LongVol_set(swigCPtr, this, value);
  }

  public int getLongVol() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_LongVol_get(swigCPtr, this);
  }

  public void setShortVol(int value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_ShortVol_set(swigCPtr, this, value);
  }

  public int getShortVol() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_ShortVol_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_Direction_get(swigCPtr, this);
  }

  public void setBadDir(char value) {
    ctpJNI.CShfeFtdcRspSafePriceRangeField_BadDir_set(swigCPtr, this, value);
  }

  public char getBadDir() {
    return ctpJNI.CShfeFtdcRspSafePriceRangeField_BadDir_get(swigCPtr, this);
  }

  public CShfeFtdcRspSafePriceRangeField() {
    this(ctpJNI.new_CShfeFtdcRspSafePriceRangeField(), true);
  }

}
