/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcSeqBizNoticeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcSeqBizNoticeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcSeqBizNoticeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcSeqBizNoticeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUniqSequenceNo(int value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_UniqSequenceNo_set(swigCPtr, this, value);
  }

  public int getUniqSequenceNo() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_UniqSequenceNo_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_TradingDay_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_SequenceNo_get(swigCPtr, this);
  }

  public void setMethod(char value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_Method_set(swigCPtr, this, value);
  }

  public char getMethod() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_Method_get(swigCPtr, this);
  }

  public void setEventTime(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_EventTime_set(swigCPtr, this, value);
  }

  public String getEventTime() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_EventTime_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_UserID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_InvestorID_get(swigCPtr, this);
  }

  public void setBizType(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_BizType_set(swigCPtr, this, value);
  }

  public String getBizType() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_BizType_get(swigCPtr, this);
  }

  public void setStatus(char value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_Status_set(swigCPtr, this, value);
  }

  public char getStatus() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_Status_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_Message_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    ctpJNI.CShfeFtdcSeqBizNoticeField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return ctpJNI.CShfeFtdcSeqBizNoticeField_ErrorMsg_get(swigCPtr, this);
  }

  public CShfeFtdcSeqBizNoticeField() {
    this(ctpJNI.new_CShfeFtdcSeqBizNoticeField(), true);
  }

}
