/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcQryProductField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcQryProductField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcQryProductField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcQryProductField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductID(String value) {
    ctpJNI.CShfeFtdcQryProductField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return ctpJNI.CShfeFtdcQryProductField_ProductID_get(swigCPtr, this);
  }

  public CShfeFtdcQryProductField() {
    this(ctpJNI.new_CShfeFtdcQryProductField(), true);
  }

}
