/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcLinkManField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcLinkManField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcLinkManField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcLinkManField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcLinkManField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcLinkManField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcLinkManField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcLinkManField_InvestorID_get(swigCPtr, this);
  }

  public void setPersonType(char value) {
    ctpJNI.CShfeFtdcLinkManField_PersonType_set(swigCPtr, this, value);
  }

  public char getPersonType() {
    return ctpJNI.CShfeFtdcLinkManField_PersonType_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    ctpJNI.CShfeFtdcLinkManField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return ctpJNI.CShfeFtdcLinkManField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ctpJNI.CShfeFtdcLinkManField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ctpJNI.CShfeFtdcLinkManField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setPersonName(String value) {
    ctpJNI.CShfeFtdcLinkManField_PersonName_set(swigCPtr, this, value);
  }

  public String getPersonName() {
    return ctpJNI.CShfeFtdcLinkManField_PersonName_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ctpJNI.CShfeFtdcLinkManField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ctpJNI.CShfeFtdcLinkManField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ctpJNI.CShfeFtdcLinkManField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ctpJNI.CShfeFtdcLinkManField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    ctpJNI.CShfeFtdcLinkManField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return ctpJNI.CShfeFtdcLinkManField_ZipCode_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    ctpJNI.CShfeFtdcLinkManField_Priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return ctpJNI.CShfeFtdcLinkManField_Priority_get(swigCPtr, this);
  }

  public CShfeFtdcLinkManField() {
    this(ctpJNI.new_CShfeFtdcLinkManField(), true);
  }

}
