/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcQryTradeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcQryTradeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcQryTradeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcQryTradeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcQryTradeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcQryTradeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcQryTradeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcQryTradeField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpJNI.CShfeFtdcQryTradeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpJNI.CShfeFtdcQryTradeField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpJNI.CShfeFtdcQryTradeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpJNI.CShfeFtdcQryTradeField_ExchangeID_get(swigCPtr, this);
  }

  public void setTradeID(String value) {
    ctpJNI.CShfeFtdcQryTradeField_TradeID_set(swigCPtr, this, value);
  }

  public String getTradeID() {
    return ctpJNI.CShfeFtdcQryTradeField_TradeID_get(swigCPtr, this);
  }

  public void setTradeTimeStart(String value) {
    ctpJNI.CShfeFtdcQryTradeField_TradeTimeStart_set(swigCPtr, this, value);
  }

  public String getTradeTimeStart() {
    return ctpJNI.CShfeFtdcQryTradeField_TradeTimeStart_get(swigCPtr, this);
  }

  public void setTradeTimeEnd(String value) {
    ctpJNI.CShfeFtdcQryTradeField_TradeTimeEnd_set(swigCPtr, this, value);
  }

  public String getTradeTimeEnd() {
    return ctpJNI.CShfeFtdcQryTradeField_TradeTimeEnd_get(swigCPtr, this);
  }

  public CShfeFtdcQryTradeField() {
    this(ctpJNI.new_CShfeFtdcQryTradeField(), true);
  }

}
