/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRiskInvestorInfoField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRiskInvestorInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRiskInvestorInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRiskInvestorInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_InvestorID_get(swigCPtr, this);
  }

  public void setMobile(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_Mobile_set(swigCPtr, this, value);
  }

  public String getMobile() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_Mobile_get(swigCPtr, this);
  }

  public void setEMail(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_EMail_set(swigCPtr, this, value);
  }

  public String getEMail() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_EMail_get(swigCPtr, this);
  }

  public void setIsEMail(int value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_IsEMail_set(swigCPtr, this, value);
  }

  public int getIsEMail() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_IsEMail_get(swigCPtr, this);
  }

  public void setIsSMS(int value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_IsSMS_set(swigCPtr, this, value);
  }

  public int getIsSMS() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_IsSMS_get(swigCPtr, this);
  }

  public void setInvestorType(char value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_InvestorType_set(swigCPtr, this, value);
  }

  public char getInvestorType() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_InvestorType_get(swigCPtr, this);
  }

  public void setPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_PhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getPhoneCountryCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_PhoneCountryCode_get(swigCPtr, this);
  }

  public void setPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_PhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getPhoneAreaCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_PhoneAreaCode_get(swigCPtr, this);
  }

  public void setOpenPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_OpenPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getOpenPhoneCountryCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_OpenPhoneCountryCode_get(swigCPtr, this);
  }

  public void setOpenPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_OpenPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getOpenPhoneAreaCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_OpenPhoneAreaCode_get(swigCPtr, this);
  }

  public void setOrderPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_OrderPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getOrderPhoneCountryCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_OrderPhoneCountryCode_get(swigCPtr, this);
  }

  public void setOrderPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_OrderPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getOrderPhoneAreaCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_OrderPhoneAreaCode_get(swigCPtr, this);
  }

  public void setFundPhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_FundPhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getFundPhoneCountryCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_FundPhoneCountryCode_get(swigCPtr, this);
  }

  public void setFundPhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_FundPhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getFundPhoneAreaCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_FundPhoneAreaCode_get(swigCPtr, this);
  }

  public void setSettlePhoneCountryCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_SettlePhoneCountryCode_set(swigCPtr, this, value);
  }

  public String getSettlePhoneCountryCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_SettlePhoneCountryCode_get(swigCPtr, this);
  }

  public void setSettlePhoneAreaCode(String value) {
    ctpJNI.CShfeFtdcRiskInvestorInfoField_SettlePhoneAreaCode_set(swigCPtr, this, value);
  }

  public String getSettlePhoneAreaCode() {
    return ctpJNI.CShfeFtdcRiskInvestorInfoField_SettlePhoneAreaCode_get(swigCPtr, this);
  }

  public CShfeFtdcRiskInvestorInfoField() {
    this(ctpJNI.new_CShfeFtdcRiskInvestorInfoField(), true);
  }

}
