/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcLogoutAllField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcLogoutAllField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcLogoutAllField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcLogoutAllField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrontID(int value) {
    ctpJNI.CShfeFtdcLogoutAllField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return ctpJNI.CShfeFtdcLogoutAllField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ctpJNI.CShfeFtdcLogoutAllField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ctpJNI.CShfeFtdcLogoutAllField_SessionID_get(swigCPtr, this);
  }

  public void setSystemName(String value) {
    ctpJNI.CShfeFtdcLogoutAllField_SystemName_set(swigCPtr, this, value);
  }

  public String getSystemName() {
    return ctpJNI.CShfeFtdcLogoutAllField_SystemName_get(swigCPtr, this);
  }

  public CShfeFtdcLogoutAllField() {
    this(ctpJNI.new_CShfeFtdcLogoutAllField(), true);
  }

}
