/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcForceCloseStandardField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcForceCloseStandardField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcForceCloseStandardField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcForceCloseStandardField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setForceCloseLevel(char value) {
    ctpJNI.CShfeFtdcForceCloseStandardField_ForceCloseLevel_set(swigCPtr, this, value);
  }

  public char getForceCloseLevel() {
    return ctpJNI.CShfeFtdcForceCloseStandardField_ForceCloseLevel_get(swigCPtr, this);
  }

  public void setForceCloseRelease(char value) {
    ctpJNI.CShfeFtdcForceCloseStandardField_ForceCloseRelease_set(swigCPtr, this, value);
  }

  public char getForceCloseRelease() {
    return ctpJNI.CShfeFtdcForceCloseStandardField_ForceCloseRelease_get(swigCPtr, this);
  }

  public void setFCNonLimitFirst(int value) {
    ctpJNI.CShfeFtdcForceCloseStandardField_FCNonLimitFirst_set(swigCPtr, this, value);
  }

  public int getFCNonLimitFirst() {
    return ctpJNI.CShfeFtdcForceCloseStandardField_FCNonLimitFirst_get(swigCPtr, this);
  }

  public CShfeFtdcForceCloseStandardField() {
    this(ctpJNI.new_CShfeFtdcForceCloseStandardField(), true);
  }

}
