/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRiskPatternField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRiskPatternField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRiskPatternField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRiskPatternField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRiskPatternField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRiskPatternField_BrokerID_get(swigCPtr, this);
  }

  public void setBizType(String value) {
    ctpJNI.CShfeFtdcRiskPatternField_BizType_set(swigCPtr, this, value);
  }

  public String getBizType() {
    return ctpJNI.CShfeFtdcRiskPatternField_BizType_get(swigCPtr, this);
  }

  public void setPatternID(int value) {
    ctpJNI.CShfeFtdcRiskPatternField_PatternID_set(swigCPtr, this, value);
  }

  public int getPatternID() {
    return ctpJNI.CShfeFtdcRiskPatternField_PatternID_get(swigCPtr, this);
  }

  public void setPatternName(String value) {
    ctpJNI.CShfeFtdcRiskPatternField_PatternName_set(swigCPtr, this, value);
  }

  public String getPatternName() {
    return ctpJNI.CShfeFtdcRiskPatternField_PatternName_get(swigCPtr, this);
  }

  public void setPattern(String value) {
    ctpJNI.CShfeFtdcRiskPatternField_Pattern_set(swigCPtr, this, value);
  }

  public String getPattern() {
    return ctpJNI.CShfeFtdcRiskPatternField_Pattern_get(swigCPtr, this);
  }

  public CShfeFtdcRiskPatternField() {
    this(ctpJNI.new_CShfeFtdcRiskPatternField(), true);
  }

}
