/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcPredictRiskAccountField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcPredictRiskAccountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcPredictRiskAccountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcPredictRiskAccountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_InvestorID_get(swigCPtr, this);
  }

  public void setBalance0(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Balance0_set(swigCPtr, this, value);
  }

  public double getBalance0() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Balance0_get(swigCPtr, this);
  }

  public void setLose1(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Lose1_set(swigCPtr, this, value);
  }

  public double getLose1() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Lose1_get(swigCPtr, this);
  }

  public void setBalance1(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Balance1_set(swigCPtr, this, value);
  }

  public double getBalance1() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Balance1_get(swigCPtr, this);
  }

  public void setLose2(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Lose2_set(swigCPtr, this, value);
  }

  public double getLose2() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Lose2_get(swigCPtr, this);
  }

  public void setBalance2(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Balance2_set(swigCPtr, this, value);
  }

  public double getBalance2() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Balance2_get(swigCPtr, this);
  }

  public void setLose3(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Lose3_set(swigCPtr, this, value);
  }

  public double getLose3() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Lose3_get(swigCPtr, this);
  }

  public void setBalance3(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Balance3_set(swigCPtr, this, value);
  }

  public double getBalance3() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Balance3_get(swigCPtr, this);
  }

  public void setLose4(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Lose4_set(swigCPtr, this, value);
  }

  public double getLose4() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Lose4_get(swigCPtr, this);
  }

  public void setBalance4(double value) {
    ctpJNI.CShfeFtdcPredictRiskAccountField_Balance4_set(swigCPtr, this, value);
  }

  public double getBalance4() {
    return ctpJNI.CShfeFtdcPredictRiskAccountField_Balance4_get(swigCPtr, this);
  }

  public CShfeFtdcPredictRiskAccountField() {
    this(ctpJNI.new_CShfeFtdcPredictRiskAccountField(), true);
  }

}
