/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcInstInvestorRangeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcInstInvestorRangeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcInstInvestorRangeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcInstInvestorRangeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ctpJNI.CShfeFtdcInstInvestorRangeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpJNI.CShfeFtdcInstInvestorRangeField_InstrumentID_get(swigCPtr, this);
  }

  public void setInvestorIDBeg(String value) {
    ctpJNI.CShfeFtdcInstInvestorRangeField_InvestorIDBeg_set(swigCPtr, this, value);
  }

  public String getInvestorIDBeg() {
    return ctpJNI.CShfeFtdcInstInvestorRangeField_InvestorIDBeg_get(swigCPtr, this);
  }

  public void setInvestorIDEnd(String value) {
    ctpJNI.CShfeFtdcInstInvestorRangeField_InvestorIDEnd_set(swigCPtr, this, value);
  }

  public String getInvestorIDEnd() {
    return ctpJNI.CShfeFtdcInstInvestorRangeField_InvestorIDEnd_get(swigCPtr, this);
  }

  public CShfeFtdcInstInvestorRangeField() {
    this(ctpJNI.new_CShfeFtdcInstInvestorRangeField(), true);
  }

}
