/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcReqInvestorOrderField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcReqInvestorOrderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcReqInvestorOrderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcReqInvestorOrderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_BrokerID_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_TradingDay_get(swigCPtr, this);
  }

  public void setInvestorIDStart(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_InvestorIDStart_set(swigCPtr, this, value);
  }

  public String getInvestorIDStart() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_InvestorIDStart_get(swigCPtr, this);
  }

  public void setInvestorIDEnd(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_InvestorIDEnd_set(swigCPtr, this, value);
  }

  public String getInvestorIDEnd() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_InvestorIDEnd_get(swigCPtr, this);
  }

  public void setInstIDStart(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_InstIDStart_set(swigCPtr, this, value);
  }

  public String getInstIDStart() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_InstIDStart_get(swigCPtr, this);
  }

  public void setInstIDEnd(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_InstIDEnd_set(swigCPtr, this, value);
  }

  public String getInstIDEnd() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_InstIDEnd_get(swigCPtr, this);
  }

  public void setProductIDStart(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_ProductIDStart_set(swigCPtr, this, value);
  }

  public String getProductIDStart() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_ProductIDStart_get(swigCPtr, this);
  }

  public void setProductIDEnd(String value) {
    ctpJNI.CShfeFtdcReqInvestorOrderField_ProductIDEnd_set(swigCPtr, this, value);
  }

  public String getProductIDEnd() {
    return ctpJNI.CShfeFtdcReqInvestorOrderField_ProductIDEnd_get(swigCPtr, this);
  }

  public CShfeFtdcReqInvestorOrderField() {
    this(ctpJNI.new_CShfeFtdcReqInvestorOrderField(), true);
  }

}
