/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcRiskNotifyAField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcRiskNotifyAField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcRiskNotifyAField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcRiskNotifyAField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSequenceNo(int value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_SequenceNo_get(swigCPtr, this);
  }

  public void setEventDate(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_EventDate_set(swigCPtr, this, value);
  }

  public String getEventDate() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_EventDate_get(swigCPtr, this);
  }

  public void setEventTime(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_EventTime_set(swigCPtr, this, value);
  }

  public String getEventTime() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_EventTime_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_UserID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_InvestorID_get(swigCPtr, this);
  }

  public void setNotifyClass(char value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_NotifyClass_set(swigCPtr, this, value);
  }

  public char getNotifyClass() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_NotifyClass_get(swigCPtr, this);
  }

  public void setNotifyMethod(char value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_NotifyMethod_set(swigCPtr, this, value);
  }

  public char getNotifyMethod() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_NotifyMethod_get(swigCPtr, this);
  }

  public void setNotifyStatus(char value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_NotifyStatus_set(swigCPtr, this, value);
  }

  public char getNotifyStatus() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_NotifyStatus_get(swigCPtr, this);
  }

  public void setMessage(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_Message_set(swigCPtr, this, value);
  }

  public String getMessage() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_Message_get(swigCPtr, this);
  }

  public void setReserve(String value) {
    ctpJNI.CShfeFtdcRiskNotifyAField_Reserve_set(swigCPtr, this, value);
  }

  public String getReserve() {
    return ctpJNI.CShfeFtdcRiskNotifyAField_Reserve_get(swigCPtr, this);
  }

  public CShfeFtdcRiskNotifyAField() {
    this(ctpJNI.new_CShfeFtdcRiskNotifyAField(), true);
  }

}
