/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcNotifySequenceField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcNotifySequenceField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcNotifySequenceField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcNotifySequenceField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSequenceNo(int value) {
    ctpJNI.CShfeFtdcNotifySequenceField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpJNI.CShfeFtdcNotifySequenceField_SequenceNo_get(swigCPtr, this);
  }

  public CShfeFtdcNotifySequenceField() {
    this(ctpJNI.new_CShfeFtdcNotifySequenceField(), true);
  }

}
