/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ctp.api;

public class CShfeFtdcTransferQryBankRspField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public CShfeFtdcTransferQryBankRspField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CShfeFtdcTransferQryBankRspField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CShfeFtdcTransferQryBankRspField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetCode(String value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_RetCode_set(swigCPtr, this, value);
  }

  public String getRetCode() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_RetCode_get(swigCPtr, this);
  }

  public void setRetInfo(String value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_RetInfo_set(swigCPtr, this, value);
  }

  public String getRetInfo() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_RetInfo_get(swigCPtr, this);
  }

  public void setFutureAccount(String value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_FutureAccount_set(swigCPtr, this, value);
  }

  public String getFutureAccount() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_FutureAccount_get(swigCPtr, this);
  }

  public void setTradeAmt(double value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_TradeAmt_set(swigCPtr, this, value);
  }

  public double getTradeAmt() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_TradeAmt_get(swigCPtr, this);
  }

  public void setUseAmt(double value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_UseAmt_set(swigCPtr, this, value);
  }

  public double getUseAmt() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_UseAmt_get(swigCPtr, this);
  }

  public void setFetchAmt(double value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_FetchAmt_set(swigCPtr, this, value);
  }

  public double getFetchAmt() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_FetchAmt_get(swigCPtr, this);
  }

  public void setCurrencyCode(String value) {
    ctpJNI.CShfeFtdcTransferQryBankRspField_CurrencyCode_set(swigCPtr, this, value);
  }

  public String getCurrencyCode() {
    return ctpJNI.CShfeFtdcTransferQryBankRspField_CurrencyCode_get(swigCPtr, this);
  }

  public CShfeFtdcTransferQryBankRspField() {
    this(ctpJNI.new_CShfeFtdcTransferQryBankRspField(), true);
  }

}
