/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CShfeFtdcRiskUserApi {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskUserApi(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskUserApi obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static CShfeFtdcRiskUserApi CreateFtdcRiskUserApi(String pszFlowPath) {
    long cPtr = ctpapiJNI.CShfeFtdcRiskUserApi_CreateFtdcRiskUserApi__SWIG_0(pszFlowPath);
    return (cPtr == 0) ? null : new CShfeFtdcRiskUserApi(cPtr, false);
  }

  public static CShfeFtdcRiskUserApi CreateFtdcRiskUserApi() {
    long cPtr = ctpapiJNI.CShfeFtdcRiskUserApi_CreateFtdcRiskUserApi__SWIG_1();
    return (cPtr == 0) ? null : new CShfeFtdcRiskUserApi(cPtr, false);
  }

  public void Release() {
    ctpapiJNI.CShfeFtdcRiskUserApi_Release(swigCPtr, this);
  }

  public void Init() {
    ctpapiJNI.CShfeFtdcRiskUserApi_Init(swigCPtr, this);
  }

  public int Join() {
    return ctpapiJNI.CShfeFtdcRiskUserApi_Join(swigCPtr, this);
  }

  public String GetTradingDay() {
    return ctpapiJNI.CShfeFtdcRiskUserApi_GetTradingDay(swigCPtr, this);
  }

  public void RegisterFront(String pszFrontAddress) {
    ctpapiJNI.CShfeFtdcRiskUserApi_RegisterFront(swigCPtr, this, pszFrontAddress);
  }

  public void RegisterSpi(CShfeFtdcRiskUserSpi pSpi) {
    ctpapiJNI.CShfeFtdcRiskUserApi_RegisterSpi(swigCPtr, this, CShfeFtdcRiskUserSpi.getCPtr(pSpi), pSpi);
  }

  public int ReqRiskUserLogin(SWIGTYPE_p_CShfeFtdcReqRiskUserLoginField pReqRiskUserLogin, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskUserLogin(swigCPtr, this, SWIGTYPE_p_CShfeFtdcReqRiskUserLoginField.getCPtr(pReqRiskUserLogin), nRequestID);
  }

  public int ReqQryOrderStat(SWIGTYPE_p_CShfeFtdcQryStatField pQryStat, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryOrderStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQryStatField.getCPtr(pQryStat), nRequestID);
  }

  public int ReqSubRiskMarketData(SWIGTYPE_p_CShfeFtdcSubMarketDataField pSubMarketData, int SubMarketDataCnt, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubRiskMarketData(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSubMarketDataField.getCPtr(pSubMarketData), SubMarketDataCnt, nRequestID);
  }

  public int ReqUnSubRiskMarketData(SWIGTYPE_p_CShfeFtdcSubMarketDataField pSubMarketData, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqUnSubRiskMarketData(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSubMarketDataField.getCPtr(pSubMarketData), nRequestID);
  }

  public int ReqQryInstPositionRate(SWIGTYPE_p_CShfeFtdcQryInstPositionRateField pQryInstPositionRate, int QryInstPositionRateCnt, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryInstPositionRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQryInstPositionRateField.getCPtr(pQryInstPositionRate), QryInstPositionRateCnt, nRequestID);
  }

  public int ReqQryProductPositionRate(SWIGTYPE_p_CShfeFtdcQryProductPositionRateField pQryProductPositionRate, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryProductPositionRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQryProductPositionRateField.getCPtr(pQryProductPositionRate), nRequestID);
  }

  public int ReqSubscribeTrade(SWIGTYPE_p_CShfeFtdcNotifySequenceField pNotifySequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubscribeTrade(swigCPtr, this, SWIGTYPE_p_CShfeFtdcNotifySequenceField.getCPtr(pNotifySequence), nRequestID);
  }

  public int ReqSubscribeOrder(SWIGTYPE_p_CShfeFtdcNotifySequenceField pNotifySequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubscribeOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcNotifySequenceField.getCPtr(pNotifySequence), nRequestID);
  }

  public int ReqSubBrokerUserEvent(SWIGTYPE_p_CShfeFtdcNotifySequenceField pNotifySequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubBrokerUserEvent(swigCPtr, this, SWIGTYPE_p_CShfeFtdcNotifySequenceField.getCPtr(pNotifySequence), nRequestID);
  }

  public int ReqRiskOrderInsert(SWIGTYPE_p_CShfeFtdcRiskForceCloseOrderField pRiskForceCloseOrder, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskOrderInsert(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskForceCloseOrderField.getCPtr(pRiskForceCloseOrder), nRequestID);
  }

  public int ReqRiskOrderAction(SWIGTYPE_p_CShfeFtdcInputOrderActionField pInputOrderAction, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskOrderAction(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInputOrderActionField.getCPtr(pInputOrderAction), nRequestID);
  }

  public int ReqSubscribePosition(SWIGTYPE_p_CShfeFtdcNotifySequenceField pNotifySequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubscribePosition(swigCPtr, this, SWIGTYPE_p_CShfeFtdcNotifySequenceField.getCPtr(pNotifySequence), nRequestID);
  }

  public int ReqRiskParkedOrderInsert(SWIGTYPE_p_CShfeFtdcRiskParkedOrderField pRiskParkedOrder, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskParkedOrderInsert(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskParkedOrderField.getCPtr(pRiskParkedOrder), nRequestID);
  }

  public int ReqRemoveRiskParkedOrder(SWIGTYPE_p_CShfeFtdcRemoveRiskParkedOrderField pRemoveRiskParkedOrder, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRemoveRiskParkedOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRemoveRiskParkedOrderField.getCPtr(pRemoveRiskParkedOrder), nRequestID);
  }

  public int ReqSubRiskParkedOrder(SWIGTYPE_p_CShfeFtdcNotifySequenceField pNotifySequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubRiskParkedOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcNotifySequenceField.getCPtr(pNotifySequence), nRequestID);
  }

  public int ReqRiskUserPasswordUpd(SWIGTYPE_p_CShfeFtdcUserPasswordUpdateField pUserPasswordUpdate, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskUserPasswordUpd(swigCPtr, this, SWIGTYPE_p_CShfeFtdcUserPasswordUpdateField.getCPtr(pUserPasswordUpdate), nRequestID);
  }

  public int ReqSubSeqDeposit(SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField pRiskNtfSequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubSeqDeposit(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField.getCPtr(pRiskNtfSequence), nRequestID);
  }

  public int ReqSubSeqTradingCode(SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField pRiskNtfSequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubSeqTradingCode(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField.getCPtr(pRiskNtfSequence), nRequestID);
  }

  public int ReqQryInvestorLinkMan(SWIGTYPE_p_CShfeFtdcInvestorIDRangeField pInvestorIDRange, int InvestorIDRangeCnt, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryInvestorLinkMan(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorIDRangeField.getCPtr(pInvestorIDRange), InvestorIDRangeCnt, nRequestID);
  }

  public int ReqQryInvestorDepartment(SWIGTYPE_p_CShfeFtdcInvestorIDRangeField pInvestorIDRange, int InvestorIDRangeCnt, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryInvestorDepartment(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorIDRangeField.getCPtr(pInvestorIDRange), InvestorIDRangeCnt, nRequestID);
  }

  public int ReqSubPreRiskAccount(SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField pRiskNtfSequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubPreRiskAccount(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField.getCPtr(pRiskNtfSequence), nRequestID);
  }

  public int ReqSubSeqData(SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField pRiskNtfSequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubSeqData(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField.getCPtr(pRiskNtfSequence), nRequestID);
  }

  public int ReqRiskQryBrokerDeposit(SWIGTYPE_p_CShfeFtdcQueryBrokerDepositField pQueryBrokerDeposit, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqRiskQryBrokerDeposit(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQueryBrokerDepositField.getCPtr(pQueryBrokerDeposit), nRequestID);
  }

  public int ReqSubSeqRiskNotifyB(SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField pRiskNtfSequence, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqSubSeqRiskNotifyB(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskNtfSequenceField.getCPtr(pRiskNtfSequence), nRequestID);
  }

  public int ReqQryPositionStat(SWIGTYPE_p_CShfeFtdcQryStatField pQryStat, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryPositionStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQryStatField.getCPtr(pQryStat), nRequestID);
  }

  public int ReqQryTradeStat(SWIGTYPE_p_CShfeFtdcQryStatField pQryStat, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqQryTradeStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQryStatField.getCPtr(pQryStat), nRequestID);
  }

  public int ReqInvestorLinkManHash(SWIGTYPE_p_CShfeFtdcInvestorIDRangeField pInvestorIDRange, int nRequestID) {
    return ctpapiJNI.CShfeFtdcRiskUserApi_ReqInvestorLinkManHash(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorIDRangeField.getCPtr(pInvestorIDRange), nRequestID);
  }

}
