/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class CShfeFtdcRiskUserSpi {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskUserSpi(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskUserSpi obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CShfeFtdcRiskUserSpi(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void OnFrontConnected() {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnFrontConnected(swigCPtr, this);
  }

  public void OnFrontDisconnected(int nReason) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnFrontDisconnected(swigCPtr, this, nReason);
  }

  public void OnHeartBeatWarning(int nTimeLapse) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnHeartBeatWarning(swigCPtr, this, nTimeLapse);
  }

  public void OnRspError(SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspError(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnBrokerDeposit(SWIGTYPE_p_CShfeFtdcBrokerDepositField pBrokerDeposit) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnBrokerDeposit(swigCPtr, this, SWIGTYPE_p_CShfeFtdcBrokerDepositField.getCPtr(pBrokerDeposit));
  }

  public void OnRtnClientSGDataSyncStart(SWIGTYPE_p_CShfeFtdcSettlementSessionField pSettlementSession) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnClientSGDataSyncStart(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSettlementSessionField.getCPtr(pSettlementSession));
  }

  public void OnRtnClientSGDataSyncEnd(SWIGTYPE_p_CShfeFtdcSettlementSessionField pSettlementSession) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnClientSGDataSyncEnd(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSettlementSessionField.getCPtr(pSettlementSession));
  }

  public void OnRspRiskUserLogin(SWIGTYPE_p_CShfeFtdcRspRiskUserLoginField pRspRiskUserLogin, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskUserLogin(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRspRiskUserLoginField.getCPtr(pRspRiskUserLogin), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnProduct(SWIGTYPE_p_CShfeFtdcProductField pProduct) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnProduct(swigCPtr, this, SWIGTYPE_p_CShfeFtdcProductField.getCPtr(pProduct));
  }

  public void OnRtnInstrument(SWIGTYPE_p_CShfeFtdcInstrumentField pInstrument) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnInstrument(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInstrumentField.getCPtr(pInstrument));
  }

  public void OnRspQryOrderStat(SWIGTYPE_p_CShfeFtdcOrderStatField pOrderStat, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspQryOrderStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcOrderStatField.getCPtr(pOrderStat), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnExchange(SWIGTYPE_p_CShfeFtdcExchangeField pExchange) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnExchange(swigCPtr, this, SWIGTYPE_p_CShfeFtdcExchangeField.getCPtr(pExchange));
  }

  public void OnRtnRiskDepthMarketData(SWIGTYPE_p_CShfeFtdcDepthMarketDataField pDepthMarketData) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnRiskDepthMarketData(swigCPtr, this, SWIGTYPE_p_CShfeFtdcDepthMarketDataField.getCPtr(pDepthMarketData));
  }

  public void OnRtnTimeSync(SWIGTYPE_p_CShfeFtdcCurrentTimeField pCurrentTime) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnTimeSync(swigCPtr, this, SWIGTYPE_p_CShfeFtdcCurrentTimeField.getCPtr(pCurrentTime));
  }

  public void OnRspInstPositionRate(SWIGTYPE_p_CShfeFtdcRspInstPositionRateField pRspInstPositionRate, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspInstPositionRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRspInstPositionRateField.getCPtr(pRspInstPositionRate), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRspProductPositionRate(SWIGTYPE_p_CShfeFtdcRspProductPositionRateField pRspProductPositionRate, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspProductPositionRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRspProductPositionRateField.getCPtr(pRspProductPositionRate), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnInvestorGroup(SWIGTYPE_p_CShfeFtdcInvestorGroupField pInvestorGroup) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnInvestorGroup(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorGroupField.getCPtr(pInvestorGroup));
  }

  public void OnRtnInstrumentMarginRate(SWIGTYPE_p_CShfeFtdcInstrumentMarginRateField pInstrumentMarginRate) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnInstrumentMarginRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInstrumentMarginRateField.getCPtr(pInstrumentMarginRate));
  }

  public void OnRtnInstrumentMarginRateAdjust(SWIGTYPE_p_CShfeFtdcInstrumentMarginRateAdjustField pInstrumentMarginRateAdjust) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnInstrumentMarginRateAdjust(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInstrumentMarginRateAdjustField.getCPtr(pInstrumentMarginRateAdjust));
  }

  public void OnRtnExchangeMarginRate(SWIGTYPE_p_CShfeFtdcExchangeMarginRateField pExchangeMarginRate) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnExchangeMarginRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcExchangeMarginRateField.getCPtr(pExchangeMarginRate));
  }

  public void OnRtnExchangeMarginRateAdjust(SWIGTYPE_p_CShfeFtdcExchangeMarginRateAdjustField pExchangeMarginRateAdjust) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnExchangeMarginRateAdjust(swigCPtr, this, SWIGTYPE_p_CShfeFtdcExchangeMarginRateAdjustField.getCPtr(pExchangeMarginRateAdjust));
  }

  public void OnRtnSequencialBrokerUserEvent(SWIGTYPE_p_CShfeFtdcSequencialBrokerUserEventField pSequencialBrokerUserEvent) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSequencialBrokerUserEvent(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSequencialBrokerUserEventField.getCPtr(pSequencialBrokerUserEvent));
  }

  public void OnRtnSequencialTrade(SWIGTYPE_p_CShfeFtdcSequencialTradeField pSequencialTrade) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSequencialTrade(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSequencialTradeField.getCPtr(pSequencialTrade));
  }

  public void OnRtnSequencialOrder(SWIGTYPE_p_CShfeFtdcSequencialOrderField pSequencialOrder) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSequencialOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSequencialOrderField.getCPtr(pSequencialOrder));
  }

  public void OnRspRiskOrderInsert(SWIGTYPE_p_CShfeFtdcInputOrderField pInputOrder, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskOrderInsert(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInputOrderField.getCPtr(pInputOrder), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRspRiskOrderAction(SWIGTYPE_p_CShfeFtdcInputOrderActionField pInputOrderAction, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskOrderAction(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInputOrderActionField.getCPtr(pInputOrderAction), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnSequencialPosition(SWIGTYPE_p_CShfeFtdcSequencialPositionField pSequencialPosition) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSequencialPosition(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSequencialPositionField.getCPtr(pSequencialPosition));
  }

  public void OnRtnDepartment(SWIGTYPE_p_CShfeFtdcDepartmentField pDepartment) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnDepartment(swigCPtr, this, SWIGTYPE_p_CShfeFtdcDepartmentField.getCPtr(pDepartment));
  }

  public void OnRspRiskParkedOrderInsert(SWIGTYPE_p_CShfeFtdcRiskParkedOrderField pRiskParkedOrder, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskParkedOrderInsert(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskParkedOrderField.getCPtr(pRiskParkedOrder), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRspRemoveRiskParkedOrder(SWIGTYPE_p_CShfeFtdcRemoveRiskParkedOrderField pRemoveRiskParkedOrder, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRemoveRiskParkedOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRemoveRiskParkedOrderField.getCPtr(pRemoveRiskParkedOrder), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnSeqRiskParkedOrder(SWIGTYPE_p_CShfeFtdcSeqRiskParkedOrderField pSeqRiskParkedOrder) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqRiskParkedOrder(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqRiskParkedOrderField.getCPtr(pSeqRiskParkedOrder));
  }

  public void OnRspRiskUserPasswordUpd(SWIGTYPE_p_CShfeFtdcUserPasswordUpdateField pUserPasswordUpdate, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskUserPasswordUpd(swigCPtr, this, SWIGTYPE_p_CShfeFtdcUserPasswordUpdateField.getCPtr(pUserPasswordUpdate), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnSeqDeposit(SWIGTYPE_p_CShfeFtdcSeqDepositField pSeqDeposit) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqDeposit(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqDepositField.getCPtr(pSeqDeposit));
  }

  public void OnRtnSeqTradingCode(SWIGTYPE_p_CShfeFtdcSeqTradingCodeField pSeqTradingCode) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqTradingCode(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqTradingCodeField.getCPtr(pSeqTradingCode));
  }

  public void OnRtnRiskInvestor(SWIGTYPE_p_CShfeFtdcRiskSyncInvestorField pRiskSyncInvestor) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnRiskInvestor(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskSyncInvestorField.getCPtr(pRiskSyncInvestor));
  }

  public void OnRspQryInvestorLinkMan(SWIGTYPE_p_CShfeFtdcInvestorLinkManField pInvestorLinkMan, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspQryInvestorLinkMan(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorLinkManField.getCPtr(pInvestorLinkMan), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnDelInstrumentMarginRate(SWIGTYPE_p_CShfeFtdcInstrumentMarginRateField pInstrumentMarginRate) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnDelInstrumentMarginRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInstrumentMarginRateField.getCPtr(pInstrumentMarginRate));
  }

  public void OnRtnDelInstrumentMarginRateAdjust(SWIGTYPE_p_CShfeFtdcInstrumentMarginRateAdjustField pInstrumentMarginRateAdjust) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnDelInstrumentMarginRateAdjust(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInstrumentMarginRateAdjustField.getCPtr(pInstrumentMarginRateAdjust));
  }

  public void OnRtnDelExchangeMarginRate(SWIGTYPE_p_CShfeFtdcExchangeMarginRateField pExchangeMarginRate) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnDelExchangeMarginRate(swigCPtr, this, SWIGTYPE_p_CShfeFtdcExchangeMarginRateField.getCPtr(pExchangeMarginRate));
  }

  public void OnRtnDelExchangeMarginRateAdjust(SWIGTYPE_p_CShfeFtdcExchangeMarginRateAdjustField pExchangeMarginRateAdjust) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnDelExchangeMarginRateAdjust(swigCPtr, this, SWIGTYPE_p_CShfeFtdcExchangeMarginRateAdjustField.getCPtr(pExchangeMarginRateAdjust));
  }

  public void OnRspQryInvestorDepartment(SWIGTYPE_p_CShfeFtdcInvestorDepartmentFlatField pInvestorDepartmentFlat, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspQryInvestorDepartment(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorDepartmentFlatField.getCPtr(pInvestorDepartmentFlat), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnInvestorDepartmentHash(SWIGTYPE_p_CShfeFtdcInvestorLinkManHashField pInvestorLinkManHash) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnInvestorDepartmentHash(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorLinkManHashField.getCPtr(pInvestorLinkManHash));
  }

  public void OnRtnRiskSyncAccount(SWIGTYPE_p_CShfeFtdcRiskSyncAccountField pRiskSyncAccount) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnRiskSyncAccount(swigCPtr, this, SWIGTYPE_p_CShfeFtdcRiskSyncAccountField.getCPtr(pRiskSyncAccount));
  }

  public void OnRtnSeqPreRiskAccount(SWIGTYPE_p_CShfeFtdcSeqPreRiskAccountField pSeqPreRiskAccount) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqPreRiskAccount(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqPreRiskAccountField.getCPtr(pSeqPreRiskAccount));
  }

  public void OnRtnSeqBizNotice(SWIGTYPE_p_CShfeFtdcSeqBizNoticeField pSeqBizNotice) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqBizNotice(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqBizNoticeField.getCPtr(pSeqBizNotice));
  }

  public void OnRspRiskQryBrokerDeposit(SWIGTYPE_p_CShfeFtdcQueryBrokerDepositField pQueryBrokerDeposit, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspRiskQryBrokerDeposit(swigCPtr, this, SWIGTYPE_p_CShfeFtdcQueryBrokerDepositField.getCPtr(pQueryBrokerDeposit), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRtnSeqRiskNotifyB(SWIGTYPE_p_CShfeFtdcSeqRiskNotifyBField pSeqRiskNotifyB) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRtnSeqRiskNotifyB(swigCPtr, this, SWIGTYPE_p_CShfeFtdcSeqRiskNotifyBField.getCPtr(pSeqRiskNotifyB));
  }

  public void OnRspQryPositionStat(SWIGTYPE_p_CShfeFtdcPositionStatField pPositionStat, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspQryPositionStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcPositionStatField.getCPtr(pPositionStat), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRspQryTradeStat(SWIGTYPE_p_CShfeFtdcTradeStatField pTradeStat, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspQryTradeStat(swigCPtr, this, SWIGTYPE_p_CShfeFtdcTradeStatField.getCPtr(pTradeStat), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public void OnRspInvestorLinkManHash(SWIGTYPE_p_CShfeFtdcInvestorLinkManHashField pInvestorLinkManHash, SWIGTYPE_p_CShfeFtdcRspInfoField pRspInfo, int nRequestID, boolean bIsLast) {
    ctpapiJNI.CShfeFtdcRiskUserSpi_OnRspInvestorLinkManHash(swigCPtr, this, SWIGTYPE_p_CShfeFtdcInvestorLinkManHashField.getCPtr(pInvestorLinkManHash), SWIGTYPE_p_CShfeFtdcRspInfoField.getCPtr(pRspInfo), nRequestID, bIsLast);
  }

  public CShfeFtdcRiskUserSpi() {
    this(ctpapiJNI.new_CShfeFtdcRiskUserSpi(), true);
  }

}
